### ISSUE TITLE
About the Twitter clean text

### ISSUE THREAD

**Issue by zzhnobug** [AndMu/Market-Wisdom#3]
hello, I have checked the twitter dataset, but I'm confused about the twitter clean text file. When I use np.unique() to check the files, it turns out that 001 has 581877 unique ids, 002 has 36879 ids, while 003 has 4265 ids. I guess a text id refers to a text, but there are more thatn 1200000 unique texts in the three files. I am now confused about this situation. Besides, is psenti.csv the sentiment extracted from those three files?
Thank you.

**Comment by AndMu** [comment]
001/002/003 Is a single file split into free files, in other case GitHub rejects file as too large.
And it is the raw original file.
You should only look at psenti.csv or its derivatives such as resultsAAPL.csv, which only includes messages mentioning AAPL.

**Comment by zzhnobug** [comment]
I try to experiment on the DJIA data. I select ids of the texts which are about 30 stocks in the original file, and then use those ids to select in the psenti.csv. That is why I'm concerned about the unique ids. If an id refers to a single text, then my selection procedure is right. But if the id in original file and the id in psenti.csv cannot match, I think there is something wrong with my procedure.
Thanks.

**Comment by AndMu** [comment]
The id should be the same. After the holidays, next week I will double check.

**Comment by AndMu** [comment]
I did the validation of files. Both original cleaned and and processed contains 1225719 records. All ids match.
